[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "functions/api"

[[functions]]
  function = "api"
  path = "/.netlify/functions/api"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"